# Build React app
FROM node:22 AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build


# Serve React app with Nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY ml-review-analysis-dashboard-prod.conf /etc/nginx/conf.d/ml-review-analysis-dashboard.conf

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]