services:
  frontend:
    image: ${ECR_REGISTRY}/ml-review-analysis-dashboard/frontend:${IMAGE_TAG}
    ports: 
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  backend:
    image: ${ECR_REGISTRY}/ml-review-analysis-dashboard/backend:${IMAGE_TAG}
    expose: 
      - "8000"