name: Build and Deploy Docker Images on push

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to deploy"
        required: true
        type: string

env:
  AWS_REGION: us-east-1
  ECR_FRONTEND_REPOSITORY: ml-review-analysis-dashboard/frontend
  ECR_BACKEND_REPOSITORY: ml-review-analysis-dashboard/backend
  ECR_REGISTRY: 596953737242.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build, tag, and push frontend docker image
      - name: Build frontend Docker image
        run: |
          docker build \
          -f ./frontend/Dockerfile-prod \
          -t $ECR_FRONTEND_REPOSITORY:${{ github.sha }} ./frontend

      - name: Tag frontend image with version
        run: |
          docker tag \
          $ECR_FRONTEND_REPOSITORY:${{ github.sha }} \
          $ECR_REGISTRY/$ECR_FRONTEND_REPOSITORY:${{ github.ref_name }}

      - name: Tag frontend image with commit SHA
        run: |
          docker tag \
          $ECR_FRONTEND_REPOSITORY:${{ github.sha }} \
          $ECR_REGISTRY/$ECR_FRONTEND_REPOSITORY:${{ github.sha }}
      
      - name: Push frontend images
        run: |
          docker push \
          $ECR_REGISTRY/$ECR_FRONTEND_REPOSITORY:${{ github.ref_name }}
      
          docker push \
          $ECR_REGISTRY/$ECR_FRONTEND_REPOSITORY:${{ github.sha }}

      
      # Build, tag, and push backend docker image
      - name: Build Backend Docker image
        run: |
          docker build \
          -f ./backend/Dockerfile-prod \
          -t $ECR_BACKEND_REPOSITORY:${{ github.sha }} ./backend

      - name: Tag backend image with version
        run: |
          docker tag \
          $ECR_BACKEND_REPOSITORY:${{ github.sha }} \
          $ECR_REGISTRY/$ECR_BACKEND_REPOSITORY:${{ github.ref_name }}

      - name: Tag backend image with commit SHA
        run: |
          docker tag \
          $ECR_BACKEND_REPOSITORY:${{ github.sha }} \
          $ECR_REGISTRY/$ECR_BACKEND_REPOSITORY:${{ github.sha }}
      
      - name: Push backend images
        run: |
          docker push \
          $ECR_REGISTRY/$ECR_BACKEND_REPOSITORY:${{ github.ref_name }}
      
          docker push \
          $ECR_REGISTRY/$ECR_BACKEND_REPOSITORY:${{ github.sha }}

      - name: Copy Compose file to EC2
        run: |
          scp -i ${{ secrets.EC2_SSH_KEY }} \
            -o StrictHostKeyChecking=no \
            docker-compose-prod.yml \
            ubuntu@${{ secrets.EC2_HOST }}:/app/docker-compose-prod.yml

  deploy:

    needs: build
    runs-on: ubuntu-latest

    steps:

      # Deploy frontend and backend docker containers using docker compose file
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        env:
          IMAGE_TAG: ${{ github.event_name == 'workflow_dispatch' && inputs.image_tag || github.ref_name }}
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE_TAG, ECR_REGISTRY

          script: |

            aws ecr get-login-password \
            --region us-east-1 | \
            docker login \
            --username AWS \
            --password-stdin \
            $ECR_REGISTRY

            docker compose -f docker-compose-prod.yml pull
            docker compose -f docker-compose-prod.yml up -d

            
